### ISSUE TITLE
missing data for Lagos

### ISSUE THREAD

**Issue by elcozy** [sink-opuba/covid-19-nigeria-api#4]
Hello!
From your COVID 19 API a data for Lagos is missing in the JSON file, 
Check image below
![image](https://user-images.githubusercontent.com/61386343/84646206-a49c0700-aef9-11ea-9eb3-07cca7a101dc.png)

**Comment by sink-opuba** [comment]
It's fixed now. Thanks for the issue @elcozy.

**Comment by elcozy** [comment]
Welcome!
